apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br1-vlan-trunk
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
      - name: ovs-br-vm
        description: |
          A dedicated OVS bridge with bond0 as a port
          allowing all VLANs and untagged traffic
        type: ovs-bridge
        state: up
        bridge:
          allow-extra-patch-ports: true
          options:
            stp: false
          port:
            - name: bond0
  ovn:
    bridge-mappings:
      - localnet: vlan-183
        bridge: ovs-br-vm
        state: present
